version: '3.3'

services:
  web:
    build:
      context: /home/src/proyecto
      dockerfile: Dockerfile
    container_name: contenedor_apache
    depends_on:
      - db
    volumes:
      - /home/src/proyecto:/var/www/html
    ports:
      - 8000:80

  db:
    container_name: contenedor_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ocean
    ports:
      - 3306:3306
